### ISSUE TITLE
Schema generator doesn't handle serializers with the same class name

### ISSUE THREAD

**Issue by mofr** [WinterFramework/winter#14]

**Comment by mofr** [comment]
@berenda-andrey Is it relevant for input dataclasses?

**Comment by berenda-andrey** [comment]
Seems still relevant, now we use name of model as dataclass name(the same problem with serializers)

**Comment by berenda-andrey** [comment]
Fixed for dataclasses, not for serializers

**Comment by mofr** [comment]
Closing because serializers are completely removed from the code base
