### ISSUE TITLE
Winter installed in a pure project is not working

### ISSUE THREAD

**Issue by pristupa** [WinterFramework/winter#146]
**Describe the bug**
Module "docstring_parser" is not found for some reason.

**To Reproduce**
- pip install winter
- Write "Hello, World" application
- Run it

**Expected behavior**
The application is working properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/13851207/74583477-fdb26780-4ff9-11ea-9f71-312b6b7dbe12.png)

**Environment(please complete the following information):**
 - OS: macOS 10.15
 - Python: CPython 3.6.3
 - Winter version: 2.3.1

**Comment by mofr** [comment]
Can't reproduce it anymore
```
mkdir testproject
cd testproject
poetry init
poetry add winter
poetry run django-admin startproject simple_api .
poetry run python manage.py runserver
```
