### ISSUE TITLE
Winter 9.4.1 installed in a pure project is not working

### ISSUE THREAD

**Issue by andrejromanov** [WinterFramework/winter#204]
**Describe the bug**
Attempt to call `import winter_django` raises exception `ModuleNotFoundError: No module named 'winter_django'`

**To Reproduce**
- `docker run -ti --rm --entrypoint="/bin/bash" python:3.8`
- `pip install winter==9.4.1`
- `python -c 'import winter_django'`

**Expected behavior**
Module is found and imported (there will be error related to lack of Django but it's expected)

**Environment(please complete the following information):**
 - OS: macOS 11.6
 - Python: CPython 3.8
 - Winter version: 9.4.1

**Additional context**
Version 9.4.0 works correctly

**Comment by zhukovqs** [comment]
@andrejromanov version 9.5.1 works fine. I think we can close this issue
